Feature/js setup
greenfrontend/task-manager pull request #17
Opened 2021-05-15 08:48 UTC by greenfrontend

2021-05-15 18:28 UTC, Ensaphelon requested changes

2021-05-15 18:28 UTC, Ensaphelon commented on package.json
> +    "lint": "node_modules/.bin/eslint app/javascript"
I think there is a way to run linter like `yarn run eslint app/javascript`

2021-05-15 18:28 UTC, Ensaphelon commented on package.json
> +    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
devDependencies

2021-05-15 18:28 UTC, Ensaphelon commented on package.json
> +    "prop-types": "^15.7.2",
devDependencies

2021-05-19 15:35 UTC, greenfrontend commented on package.json
> +    "lint": "node_modules/.bin/eslint app/javascript"
Fixed

2021-05-19 15:35 UTC, greenfrontend commented on package.json
> +    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
Fixed

2021-05-19 15:35 UTC, greenfrontend commented on package.json
> +    "prop-types": "^15.7.2",
Fixed

2021-05-19 16:01 UTC, Ensaphelon commented on package.json
> +    "material-design-lite": "^1.3.0",
Не уверен что оно должно быть в devDependencies)

2021-05-20 05:46 UTC, greenfrontend commented on package.json
> +    "material-design-lite": "^1.3.0",
поправил!

2021-05-20 17:47 UTC, Ensaphelon requested changes

2021-05-20 17:47 UTC, Ensaphelon commented on .eslintrc
> +    ],
Правила для eslint-а придумывали не для того чтобы их отключать в таком количестве) "react/no-array-index-key" - с этим например что не так?

2021-05-20 17:47 UTC, Ensaphelon commented on .eslintrc
> +    "import/no-duplicates": [
это правило должно быть включенным

2021-05-20 17:47 UTC, Ensaphelon commented on .eslintrc
> +    ],
Короче, давай оставим выключенными только те правила, в которых мы на 100% уверены что они нам только мешают. С виду кажется что тебе было лень исправлять ошибки в коде и ты просто выключил правила.

2021-05-20 18:18 UTC, greenfrontend reviewed
отправил

2021-05-25 04:10 UTC, merged