Feature/js tasks
greenfrontend/task-manager pull request #20
Opened 2021-06-03 17:02 UTC by greenfrontend

2021-06-09 13:07 UTC, Ensaphelon requested changes

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const showUpdateButton = count < totalCount;
isUpdateButtonVisible

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const totalCountToShow = !Number.isNaN(totalCount) ? totalCount : '...';
а что это за состояние когда totalCount будет равен NaN?

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
onClick={handleLoadMore}

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +            disabled={isLoading || isSaving}
давай вынесем isLoading || isSaving в константу

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/Task/Task.js
> +  const handleClick = () => {
`handle{What?}Click`

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/Task/Task.js
> +  const handleClick = () => {
надо отразить ту штуку на которой нажимаем в названии функции

2021-06-09 13:07 UTC, Ensaphelon commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => generateBoard(), [boardCards]);
не нужно создавать анонимную функцию чтобы вызвать другую без параметров

2021-06-10 17:55 UTC, greenfrontend commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const showUpdateButton = count < totalCount;
поправил

2021-06-10 18:51 UTC, greenfrontend commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const totalCountToShow = !Number.isNaN(totalCount) ? totalCount : '...';
totalCount будет равен undefined когда задачи еще не загрузились, переписал код, добавил хелпер функцию для этого

2021-06-10 18:57 UTC, greenfrontend commented on app/javascript/components/Task/Task.js
> +  const handleClick = () => {
поправил (handleTaskEditClick)

2021-06-10 18:57 UTC, greenfrontend commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => generateBoard(), [boardCards]);
поправил

2021-06-16 12:39 UTC, Ensaphelon approved these changes

2021-06-16 15:08 UTC, merged