Add redux
greenfrontend/task-manager pull request #22
Opened 2021-12-21 18:57 UTC by greenfrontend

2021-12-22 06:57 UTC, greybutton requested changes

2021-12-22 06:57 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +  setTask: PropTypes.func.isRequired,
зачем setTask? он не используется

2021-12-22 06:57 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +    },
setTask получается вообще не нужен, здесь всегда задача ставится в стор, а setTask нигде не вызывается

2021-12-22 06:57 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    await updateTask(updatedTask.id, params).unwrap();
для чего unwrap? что он делает?

2021-12-22 16:42 UTC, greenfrontend commented on app/javascript/components/EditPopup/EditPopup.js
> +  setTask: PropTypes.func.isRequired,
[вот здесь используется](https://github.com/greenfrontend/task-manager/blob/d4a8553e9d89fa8ce0580b58fe8837e51ac3a069/app/javascript/components/EditPopup/EditPopup.js#L68) видимо в diff не попало

2021-12-22 16:42 UTC, greenfrontend commented on app/javascript/slices/TasksSlice.js
> +    },
выше ответил

2021-12-22 17:05 UTC, greenfrontend commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    await updateTask(updatedTask.id, params).unwrap();
[docs](https://redux-toolkit.js.org/api/createAsyncThunk#unwrapping-result-actions)
>The thunks generated by createAsyncThunk will always return a resolved promise with either the fulfilled action object or rejected action object inside, as appropriate.

без этого ошибка в catch не попадет там, где вызовется handleTaskUpdate (если на бекенде пойдет что-то не так)

2021-12-23 06:46 UTC, greybutton approved these changes

2021-12-23 07:26 UTC, merged