Feature/devops coveralls
greenfrontend/task-manager pull request #25
Opened 2021-12-23 17:32 UTC by greenfrontend

2021-12-24 15:37 UTC, greybutton requested changes

2021-12-24 15:37 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start('rails')
генерацию покрытия нужно делать только в CI

2021-12-24 16:02 UTC, greenfrontend commented on test/test_helper.rb
> +SimpleCov.start('rails')
почему? 
а если я хочу локально посмотреть сколько кода покрыто? тем более папка /coverage в .gitignore

2021-12-24 16:02 UTC, greenfrontend commented on test/test_helper.rb
> +SimpleCov.start('rails')
@greybutton

2021-12-24 18:55 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start('rails')
в разработке тесты активно используются, ждать генерацию покрытия на каждый локальный `rails test` сомнительная затея. `rails test` запускают, чтобы проверить все тесты в проекте, а не покрытие проверить. Если локально надо посмотреть покрытие, то это можно сделать отдельно, по умолчанию генерация не нужна

2021-12-25 05:37 UTC, greenfrontend commented on test/test_helper.rb
> +SimpleCov.start('rails')
понял, спасибо

2021-12-27 06:11 UTC, greybutton approved these changes

2021-12-27 14:22 UTC, merged