Add newrelic
greenfrontend/task-manager pull request #29
Opened 2021-12-25 10:48 UTC by greenfrontend

2021-12-27 06:12 UTC, greybutton requested changes

2021-12-27 06:12 UTC, greybutton commented on newrelic.yml
> +  license_key: f5470d025887a94deaa76e624103a93b1166NRAL
ключи/токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2021-12-29 16:11 UTC, greenfrontend commented on newrelic.yml
> +  license_key: f5470d025887a94deaa76e624103a93b1166NRAL
спасибо, поправил

2021-12-29 18:59 UTC, greybutton approved these changes

2021-12-30 06:48 UTC, merged